### PR TITLE
Fixes missing url/emoji icons in payload

### PR DESCRIPTION
**Pull request by adamdburton**

### CODE REVIEW

**Comment by adamdburton** [comment]
Bump! It'd be great to get this merged as currently message icons do not work.

**Comment by gaurav1068** [comment]
will create a release

**Comment by adamdburton** [comment]
Any news on the release please?

**Comment by gaurav1068** [comment]
will merge post fixing https://github.com/razorpay/slack/issues/20

**Comment by gaurav1068** [comment]
@adamdburton created new release

**Pull request merged**
